from .interfaces.users import SteamUsers


class STEAMWORKS:
    app_id: int
    Users: SteamUsers
    def __init__(self, supported_platforms: list[str] = ...) -> None: ...
    def initialize(self) -> bool: ...
    def relaunch(self, app_id: int) -> bool: ...
    def unload(self) -> None: ...
    def loaded(self) -> bool: ...
    def run_callbacks(self) -> bool: ...
    def run_forever(self, base_interval: float = ...) -> None: ...
