"""Initial tables

Revision ID: e3d0aa17fbf3
Revises:
Create Date: 2022-04-24 13:08:30.274749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3d0aa17fbf3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("channel", sa.Integer(), nullable=False),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column("removed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("channel", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("player_turn", sa.String(), nullable=True),
        sa.Column(
            "message_type",
            sa.Enum("ERROR", "NEW_TURN", "REMINDER", "GAME_COMPLETE", "WAITING", "READY", name="messagetype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.Integer(), nullable=False),
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("wingspan_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription")
    op.drop_table("status_message")
    op.drop_table("match")
    # ### end Alembic commands ###
