"""Add score table

Revision ID: e459df704c3e
Revises: e3d0aa17fbf3
Create Date: 2022-04-27 02:21:48.859591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e459df704c3e'
down_revision = 'e3d0aa17fbf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'score',
        sa.Column('match_id', sa.String(), nullable=False),
        sa.Column('player_name', sa.String(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('bird_points', sa.Integer(), nullable=False),
        sa.Column('bonus_card_points', sa.Integer(), nullable=False),
        sa.Column('goals_points', sa.Integer(), nullable=False),
        sa.Column('eggs_points', sa.Integer(), nullable=False),
        sa.Column('cached_food_points', sa.Integer(), nullable=False),
        sa.Column('tucked_cards_points', sa.Integer(), nullable=False),
        sa.Column('food_tokens', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('match_id', 'player_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
