from ctypes import *

class FindLeaderboardResult_t(Structure): ...
class CreateItemResult_t(Structure): ...
class SubmitItemUpdateResult_t(Structure): ...
class ItemInstalled_t(Structure): ...
class RemoteStorageSubscribePublishedFileResult_t(Structure): ...
class RemoteStorageUnsubscribePublishedFileResult_t(Structure): ...
class MicroTxnAuthorizationResponse_t(Structure): ...
