from ctypes import *
from steamworks.enums import *
from steamworks.structs import *
from steamworks.exceptions import *
from enum import Enum as Enum
from typing import Any

class SteamUsers:
    steam: Any
    def __init__(self, steam: object) -> None: ...
    def GetSteamID(self) -> int: ...
    def LoggedOn(self) -> bool: ...
    def GetPlayerSteamLevel(self) -> int: ...
    def GetGameBadgeLevel(self, series: int, foil: int) -> int: ...
    def GetAuthSessionTicket(self) -> str: ...
