from ctypes import *
from steamworks.enums import *
from steamworks.structs import *
from steamworks.exceptions import *
from enum import Enum as Enum
from typing import Any

class SteamApps:
    steam: Any
    def __init__(self, steam: object) -> None: ...
    def IsSubscribed(self) -> bool: ...
    def IsLowViolence(self) -> bool: ...
    def IsCybercafe(self) -> bool: ...
    def IsVACBanned(self) -> bool: ...
    def GetCurrentGameLanguage(self) -> str: ...
    def GetAvailableGameLanguages(self) -> str: ...
    def IsSubscribedApp(self, app_id: int) -> bool: ...
    def IsDLCInstalled(self, dlc_id: int) -> bool: ...
    def GetEarliestPurchaseUnixTime(self, app_id: int) -> int: ...
    def IsSubscribedFromFreeWeekend(self) -> bool: ...
    def GetDLCCount(self) -> int: ...
    def InstallDLC(self, dlc_id: int) -> None: ...
    def UninstallDLC(self, dlc_id: int) -> None: ...
    def MarkContentCorrupt(self, missing_files_only: bool = ...) -> bool: ...
    def GetAppInstallDir(self, app_id: int) -> str: ...
    def IsAppInstalled(self, app_id: int) -> bool: ...
    def GetAppOwner(self) -> int: ...
    def GetLaunchQueryParam(self, key: str) -> str: ...
    def GetAppBuildId(self) -> int: ...
    def GetFileDetails(self, filename: str) -> None: ...
