from ctypes import *
from enum import Enum as Enum
from typing import Any

class SteamFriends:
    steam: Any
    def __init__(self, steam: object) -> None: ...
    def GetFriendCount(self, flag: bytes = ...) -> int: ...
    def GetFriendByIndex(self, friend_index: int, flag: bytes = ...) -> int: ...
    def GetPlayerName(self) -> str: ...
    def GetPlayerState(self) -> int: ...
    def GetFriendPersonaName(self, steam_id: int) -> str: ...
    def SetGameInfo(self, server_key: str, server_value: str) -> None: ...
    def ClearGameInfo(self) -> None: ...
    def InviteFriend(self, steam_id: int, connection: str) -> None: ...
    def SetPlayedWith(self, steam_id: int) -> None: ...
    def ActivateGameOverlay(self, dialog: str = ...) -> None: ...
    def ActivateGameOverlayToUser(self, dialog: str, steam_id: int) -> None: ...
    def ActivateGameOverlayToWebPage(self, url: str) -> None: ...
    def ActivateGameOverlayToStore(self, app_id: int) -> None: ...
    def ActivateGameOverlayInviteDialog(self, steam_lobby_id: int) -> None: ...
