from ctypes import *
from steamworks.enums import *
from steamworks.structs import *
from steamworks.exceptions import *
from enum import Enum as Enum
from typing import Any

class SteamMatchmaking:
    steam: Any
    def __init__(self, steam: object) -> None: ...
    def CreateLobby(self, lobby_type: int, max_members: int) -> None: ...
    def JoinLobby(self, steam_lobby_id: int) -> None: ...
    def LeaveLobby(self, steam_lobby_id: int) -> None: ...
    def InviteUserToLobby(self, steam_lobby_id: int, steam_id: int) -> bool: ...
